//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantinho_Caseiro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CantinhoCaseiroEntities1 : DbContext
    {
        public CantinhoCaseiroEntities1()
            : base("name=CantinhoCaseiroEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PedidosLocais> PedidosLocais { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
