//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantinho_Caseiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosLocais
    {
        public int Id { get; set; }
        public string PdcPrato { get; set; }
        public string PdcQuantidade { get; set; }
        public string PdcCliente { get; set; }
        public Nullable<System.DateTime> PdcData { get; set; }
        public string PdcAdcional { get; set; }
    }
}
