//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantinho_Caseiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string UsrNome { get; set; }
        public string UsrEmail { get; set; }
        public string UsrSenha { get; set; }
        public string UsrPerfil { get; set; }
        public string UsrTel { get; set; }
        public string UsrRua { get; set; }
        public string UsrNum { get; set; }
        public string UsrBairro { get; set; }
        public string UsrCidade { get; set; }
        public Nullable<System.DateTime> UsrData { get; set; }
    }
}
